### PR TITLE
Allow user to configure cache directory

### PR DESCRIPTION
**Pull request by jacobdufault**

### CODE REVIEW

**Comment by rianneogi** [comment]
Is it working for you? Can you tell me what other packages you have installed on atom, and whether you are using windows or linux?

For me, I got cquery to stop crashing but it doesn't show output (diagnostics etc.) on the UI.

**Comment by jacobdufault** [comment]
Yep, I just have ide-cquery, atom-ide-ui, narrow, and vim-mode-plus installed. https://github.com/rianneogi/ide-cquery/commit/464186957950f0d247e9d3614fd589e54b17ff26 works for me.

What errors do you get? Try `atom.config.set('core.debugLSP', true)` as documented in https://github.com/atom/atom-languageclient/blob/master/README.md

**Comment by rianneogi** [comment]
It seems cquery is quiting with return code 3221225477 right after initialization.
I don't know whether it is crashing or it is closing voluntarily.
Here is the log file:
```
arguments: C:\\Documents\\Code\\Clones\\cquery-master\\build\\release\\bin\\cquery --log-file cquerylog.txt --language-server
Current dir: C:\Documents\Code\Projects\EvoBit
File verbosity level: 9
date       time         ( uptime  ) [ thread name/id ]                   file:line     v| 
2018-01-07 14:10:28.903 (   0.000s) [main thread     ]             loguru.hpp:2012     0| Logging to 'cquerylog.txt', mode: 'w', verbosity: 9
2018-01-07 14:10:29.244 (   0.341s) [querydb         ]          initialize.cc:47       0| Init parameters: {"compilationDatabaseDirectory":"","cacheDirectory":"C:/Documents/Code/Projects/EvoBit/.vscode/cquery_cached_index/","resourceDirectory":"","extraClangArguments":[],"indexWhitelist":[],"indexBlacklist":[],"logSkippedPathsForIndex":false,"maxWorkspaceSearchResults":500,"indexerCount":0,"enableIndexing":true,"enableCacheWrite":true,"enableCacheRead":true,"enableProgressReports":true,"includeCompletionMaximumPathLength":30,"includeCompletionWhitelistLiteralEnding":[],"includeCompletionWhitelist":[],"includeCompletionBlacklist":[],"showDocumentLinksOnIncludes":true,"diagnosticsOnParse":true,"diagnosticsOnCodeCompletion":true,"codeLensOnLocalVariables":true,"enableSnippetInsertion":true}
2018-01-07 14:10:29.244 (   0.341s) [querydb         ]          initialize.cc:51       0| [querydb] Initialize in directory C:/Documents/Code/Projects/EvoBit/ with uri file:///C:/Documents/Code/Projects/EvoBit/
2018-01-07 14:10:29.244 (   0.341s) [querydb         ]          initialize.cc:94       0| Using -resource-dir=C:/Documents/Code/Clones/cquery-master/build/release/lib/LLVM-5.0.1-win64/lib/clang/5.0.1
2018-01-07 14:10:29.244 (   0.341s) [stdout          ]               timer.cc:38       0| [e2e] Running initialize took 0.185ms
2018-01-07 14:10:29.244 (   0.341s) [querydb         ]             project.cc:287      0| 
```

atom-languageclient is also showing errors like 'Connection is closed (to LSP process)' but that is probably a consequence of the crash.

**Comment by rianneogi** [comment]
The error code seems random but it is consistent throughout multiple crashes.

**Comment by jacobdufault** [comment]
I wonder if you're experience the same crash as appveyor / CI, I'm looking into it now.

**Comment by rianneogi** [comment]
I piped the stdin/out/err data to different files. Hopefully, it will help for debugging.

stderr.txt:
```
Wrote crash dump file "C:\Users\RIANNE~1\AppData\Local\Temp\cquery.exe-ea298d.dmp"
0x000000013FA07661 (0x000000000029E328 0x000000000029E740 0x000000000029E740 0x000000000029E2F0)
0x000000013FA0761A (0x0000000000000000 0x0000000000000000 0x000000000029E2A8 0x000000013FAACF04)
0x000000013F9E65C5 (0x000000000029E2A0 0x0000000000000008 0x0000000000000000 0x00000000772226A6)
0x000000013F9951C4 (0x000000000043E3E0 0x0000000000000000 0x000000000029EB60 0x000000000043E3E0)
0x000000013F994C0F (0x000000000043E360 0x000000000043E360 0x000000013FB2A7D0 0x0000000000000000)
0x000000013F9674C5 (0x0000000000000000 0x0000000000431940 0x000000000029ED68 0x0000000000000000)
0x000000013F966771 (0x0000000000434410 0x000000000029ED68 0x00000000004344A8 0x000000000043B688)
0x000000013F9111BA (0x000000000043E360 0x000000000029F090 0x00000000004442F0 0x000000000043E360)
0x000000013F911866 (0x000000000029FAD0 0x000000000029FAD0 0x000000000029F970 0x000000000043E360)
0x000000013F910E3D (0x000000000043E360 0x0333333333333332 0x000000000000003F 0x000000000043B5B0)
0x000000013F91519E (0x0000000000000000 0x0000000000000000 0x000000013FB2D5F8 0x0000000000000000)
0x000000013FA2A7D1 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000)
0x0000000076FC59CD (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), BaseThreadInitThunk() + 0xD bytes(s)
0x00000000771FB891 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), RtlUserThreadStart() + 0x21 bytes(s)
```
stdout.txt:
```
Content-Length: 161

{"jsonrpc":"2.0","method":"$cquery/progress","params":{"indexRequestCount":0,"doIdMapCount":0,"loadPreviousIndexCount":0,"onIdMappedCount":0,"onIndexedCount":0}}Content-Length: 598

{"jsonrpc":"2.0","id":0,"result":{"capabilities":{"textDocumentSync":2,"hoverProvider":true,"completionProvider":{"resolveProvider":false,"triggerCharacters":[".",":",">","#"]},"signatureHelpProvider":{"triggerCharacters":["(",","]},"definitionProvider":true,"referencesProvider":true,"documentHighlightProvider":true,"documentSymbolProvider":true,"workspaceSymbolProvider":true,"codeActionProvider":true,"codeLensProvider":{"resolveProvider":false},"documentFormattingProvider":false,"documentRangeFormattingProvider":false,"renameProvider":true,"documentLinkProvider":{"resolveProvider":false}}}}
```

stdin.txt was empty.

**Comment by jacobdufault** [comment]
Can you rerun `python waf configure` and `python waf build`? I've just pushed some fixes.

**Comment by jacobdufault** [comment]
Notably https://github.com/jacobdufault/cquery/commit/46a59dd372e578f73aac0762b927c5a3d892e386

**Comment by rianneogi** [comment]
Working now. Awesome!

**Pull request merged**
